package Swing;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;

import Components.DialogButton;
import Components.PopupBackground;
import Database.Database;
import static javax.swing.JOptionPane.showMessageDialog;


public class PopupDialogDelete extends JDialog {

    private final JFrame frame;
    private final String city;
    private ImageIcon icon;
    
    public PopupDialogDelete(JFrame frame, String city) {
        super(frame, true);
        initComponents();
        this.frame = frame;
        this.city = city;
        setLocationRelativeTo(null);
        init();
    }
    
    private void init(){
       cancelButton.setColor1(Color.decode("#4d4d4d"));
       cancelButton.setColor2(Color.decode("#333333"));
       icon = iconRender("/Icons/warning.png", 40, 40);
       warningLabel.setIcon(icon);
    }
    
    private ImageIcon iconRender(String path, int w, int h){
        ImageIcon tempIcon = new ImageIcon(getClass().getResource(path));
        Image img = tempIcon.getImage();
        Image newimg = img.getScaledInstance(w, h, Image.SCALE_SMOOTH);
        ImageIcon newIcon = new ImageIcon(newimg);
        return newIcon;        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupBackground2 = new PopupBackground();
        jLabel3 = new JLabel();
        cancelButton = new DialogButton();
        deleteButton = new DialogButton();
        jPanel1 = new JPanel();
        warningLabel = new JLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new Color(10, 10, 10));
        setUndecorated(true);

        jLabel3.setFont(new Font("Avenir Next", 0, 18)); // NOI18N
        jLabel3.setForeground(new Color(220, 220, 220));
        jLabel3.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel3.setText("<html>This action will permanently delete all data from the selected city. Do you want to proceed?</html> ");
        jLabel3.setHorizontalTextPosition(SwingConstants.CENTER);

        cancelButton.setForeground(new Color(220, 220, 220));
        cancelButton.setText("CANCEL");
        cancelButton.setFont(new Font("Avenir Next", 1, 14)); // NOI18N
        cancelButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        deleteButton.setForeground(new Color(220, 220, 220));
        deleteButton.setText("DELETE");
        deleteButton.setFont(new Font("Avenir Next", 1, 14)); // NOI18N
        deleteButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new Color(20, 20, 20));

        warningLabel.setFont(new Font("Avenir Next", 1, 24)); // NOI18N
        warningLabel.setForeground(new Color(239, 64, 76));
        warningLabel.setHorizontalAlignment(SwingConstants.CENTER);
        warningLabel.setText("WARNING");

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(warningLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(warningLabel, GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        GroupLayout popupBackground2Layout = new GroupLayout(popupBackground2);
        popupBackground2.setLayout(popupBackground2Layout);
        popupBackground2Layout.setHorizontalGroup(
            popupBackground2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(popupBackground2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(popupBackground2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, popupBackground2Layout.createSequentialGroup()
                        .addComponent(cancelButton, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(deleteButton, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 350, GroupLayout.PREFERRED_SIZE))
                .addGap(0, 20, Short.MAX_VALUE))
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        popupBackground2Layout.setVerticalGroup(
            popupBackground2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, popupBackground2Layout.createSequentialGroup()
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(popupBackground2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(popupBackground2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(popupBackground2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void deleteButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        Database connectDB = Database.getConnectionInstance();
        connectDB.DeleteDataByCity(city);
        dispose();
        showMessageDialog(null, "Meteo Data for city " + city+ " got deleted from the db");
    }//GEN-LAST:event_deleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private DialogButton cancelButton;
    private DialogButton deleteButton;
    private JLabel jLabel3;
    private JPanel jPanel1;
    private PopupBackground popupBackground2;
    private JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
}
