package Swing;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;


public class PopupDialogExit extends javax.swing.JDialog {

    private final JFrame frame;
    private ImageIcon icon, logo;
    
    public PopupDialogExit(JFrame frame) {
        super(frame, true);
        initComponents();
        this.frame = frame;
        setLocationRelativeTo(null);
        init();
    }
    
    private void init(){
       
       icon = iconRender("/Icons/exit.png", 36, 36);
       logo = iconRender("/Icons/logo2.png", 60, 48);
       cnclButton.setColor1(Color.decode("#4d4d4d"));
       cnclButton.setColor2(Color.decode("#333333"));
       extLabel.setIcon(icon);
       msg.setIcon(logo);
    }
    
    private ImageIcon iconRender(String path, int w, int h){
        ImageIcon tempIcon = new ImageIcon(getClass().getResource(path));
        Image img = tempIcon.getImage();
        Image newimg = img.getScaledInstance(w, h, java.awt.Image.SCALE_SMOOTH);
        ImageIcon newIcon = new ImageIcon(newimg);
        return newIcon;        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupBackground1 = new Components.PopupBackground();
        jPanel1 = new javax.swing.JPanel();
        extLabel = new javax.swing.JLabel();
        cnclButton = new Components.DialogButton();
        extButton = new Components.DialogButton();
        msg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(50, 50, 50));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(20, 20, 20));
        jPanel1.setForeground(new java.awt.Color(239, 64, 76));
        jPanel1.setFont(new java.awt.Font("Avenir Next", 1, 24)); // NOI18N

        extLabel.setFont(new java.awt.Font("Avenir Next", 1, 24)); // NOI18N
        extLabel.setForeground(new java.awt.Color(239, 64, 76));
        extLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        extLabel.setText("EXIT");
        extLabel.setIconTextGap(7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(extLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(extLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        cnclButton.setForeground(new java.awt.Color(220, 220, 220));
        cnclButton.setText("CANCEL");
        cnclButton.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        cnclButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnclButtonActionPerformed(evt);
            }
        });

        extButton.setForeground(new java.awt.Color(220, 220, 220));
        extButton.setText("EXIT");
        extButton.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        extButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extButtonActionPerformed(evt);
            }
        });

        msg.setFont(new java.awt.Font("Avenir Next", 0, 18)); // NOI18N
        msg.setForeground(new java.awt.Color(220, 220, 220));
        msg.setText("<html>Do you really want exit?<html>");
        msg.setIconTextGap(6);

        javax.swing.GroupLayout popupBackground1Layout = new javax.swing.GroupLayout(popupBackground1);
        popupBackground1.setLayout(popupBackground1Layout);
        popupBackground1Layout.setHorizontalGroup(
            popupBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, popupBackground1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(popupBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(msg)
                    .addGroup(popupBackground1Layout.createSequentialGroup()
                        .addComponent(cnclButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(extButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        popupBackground1Layout.setVerticalGroup(
            popupBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popupBackground1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msg, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(popupBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cnclButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(extButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(popupBackground1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(popupBackground1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cnclButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnclButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cnclButtonActionPerformed

    private void extButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_extButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Components.DialogButton cnclButton;
    private Components.DialogButton extButton;
    private javax.swing.JLabel extLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel msg;
    private Components.PopupBackground popupBackground1;
    // End of variables declaration//GEN-END:variables
}