package Swing;

import java.awt.*;
import java.awt.event.*;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;
import javax.swing.*;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

import Components.ComboBox;
import Components.DialogButton;
import Components.PopupBackground;
import Database.Database;

import static javax.swing.JOptionPane.showMessageDialog;


public class PopupDialogEdit extends JDialog {

    private final String selectedCity;
    private JFrame parent;
    private ImageIcon icon;
    
    public PopupDialogEdit(JFrame parent, String selectedCity) {
        super(parent, true);
        this.parent = parent;
        this.selectedCity = selectedCity;
        initComponents();
        setLocationRelativeTo(null);
    }
    
    private void init(){
       
       icon = iconRender("/Icons/edit.png", 36, 36);
       headingLabel.setIcon(icon);
       cnclButton.setColor1(Color.decode("#4d4d4d"));
       cnclButton.setColor2(Color.decode("#333333"));
       saveButton.setColor1(Color.decode("#e68a00"));
       saveButton.setColor2(Color.decode("#995c00"));
    }
    
    private ImageIcon iconRender(String path, int w, int h){
        ImageIcon tempIcon = new ImageIcon(getClass().getResource(path));
        Image img = tempIcon.getImage();
        Image newimg = img.getScaledInstance(w, h, Image.SCALE_SMOOTH);
        ImageIcon newIcon = new ImageIcon(newimg);
        return newIcon;        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupBackground1 = new PopupBackground();
        jPanel1 = new JPanel();
        headingLabel = new JLabel();
        comboBox1 = new ComboBox();
        button1 = new Button();
        tempTxtField = new JFormattedTextField();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        huTxtField = new JFormattedTextField();
        jLabel3 = new JLabel();
        wsTxtField = new JFormattedTextField();
        jLabel4 = new JLabel();
        uvTxtField = new JFormattedTextField();
        jLabel5 = new JLabel();
        jTextField1 = new JTextField();
        cnclButton = new DialogButton();
        saveButton = new DialogButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new Color(20, 20, 20));

        headingLabel.setFont(new Font("Avenir Next", 1, 18)); // NOI18N
        headingLabel.setForeground(new Color(120, 120, 120));
        headingLabel.setHorizontalAlignment(SwingConstants.CENTER);
        headingLabel.setText("Edit Weather Data");
        headingLabel.setIconTextGap(6);

        comboBox1.addFocusListener(new FocusAdapter() {
            public void focusGained(FocusEvent evt) {
                comboBox1FocusGained(evt);
            }
        });

        button1.setText("get");
        button1.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                button1MouseClicked(evt);
            }
        });
        button1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headingLabel, GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(comboBox1, GroupLayout.PREFERRED_SIZE, 194, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headingLabel, GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(button1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tempTxtField.setForeground(new Color(0, 0, 0));
        tempTxtField.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(NumberFormat.getIntegerInstance())));
        tempTxtField.setFocusLostBehavior(JFormattedTextField.PERSIST);
        tempTxtField.setFont(new Font("Avenir Next", 0, 12)); // NOI18N
        tempTxtField.setSelectedTextColor(new Color(0, 0, 0));

        jLabel1.setFont(new Font("Avenir Next", 0, 12)); // NOI18N
        jLabel1.setForeground(new Color(220, 220, 220));
        jLabel1.setHorizontalAlignment(SwingConstants.TRAILING);
        jLabel1.setText("Temperature:");

        jLabel2.setFont(new Font("Avenir Next", 0, 12)); // NOI18N
        jLabel2.setForeground(new Color(220, 220, 220));
        jLabel2.setHorizontalAlignment(SwingConstants.TRAILING);
        jLabel2.setText("Humidity:");

        huTxtField.setForeground(new Color(0, 0, 0));
        huTxtField.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0%"))));
        huTxtField.setFocusLostBehavior(JFormattedTextField.PERSIST);
        huTxtField.setFont(new Font("Avenir Next", 0, 12)); // NOI18N
        huTxtField.setSelectedTextColor(new Color(0, 0, 0));

        jLabel3.setFont(new Font("Avenir Next", 0, 12)); // NOI18N
        jLabel3.setForeground(new Color(220, 220, 220));
        jLabel3.setHorizontalAlignment(SwingConstants.TRAILING);
        jLabel3.setText("Windspeed:");

        wsTxtField.setForeground(new Color(0, 0, 0));
        wsTxtField.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(NumberFormat.getIntegerInstance())));
        wsTxtField.setFocusLostBehavior(JFormattedTextField.PERSIST);
        wsTxtField.setFont(new Font("Avenir Next", 0, 12)); // NOI18N
        wsTxtField.setSelectedTextColor(new Color(0, 0, 0));

        jLabel4.setFont(new Font("Avenir Next", 0, 12)); // NOI18N
        jLabel4.setForeground(new Color(220, 220, 220));
        jLabel4.setHorizontalAlignment(SwingConstants.TRAILING);
        jLabel4.setText("UV Index:");

        uvTxtField.setForeground(new Color(0, 0, 0));
        uvTxtField.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(NumberFormat.getIntegerInstance())));
        uvTxtField.setFocusLostBehavior(JFormattedTextField.PERSIST);
        uvTxtField.setFont(new Font("Avenir Next", 0, 12)); // NOI18N
        uvTxtField.setSelectedTextColor(new Color(0, 0, 0));

        jLabel5.setFont(new Font("Avenir Next", 0, 12)); // NOI18N
        jLabel5.setForeground(new Color(220, 220, 220));
        jLabel5.setHorizontalAlignment(SwingConstants.TRAILING);
        jLabel5.setText("Conditions:");

        jTextField1.setFont(new Font("Avenir Next", 0, 12)); // NOI18N
        jTextField1.setForeground(new Color(0, 0, 0));
        jTextField1.setText(" ");
        jTextField1.setToolTipText("");
        jTextField1.setDisabledTextColor(new Color(187, 187, 187));
        jTextField1.setSelectedTextColor(new Color(0, 0, 0));

        cnclButton.setForeground(new Color(220, 220, 220));
        cnclButton.setText("CANCEL");
        cnclButton.setFont(new Font("Avenir Next", 1, 14)); // NOI18N
        cnclButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cnclButtonActionPerformed(evt);
            }
        });

        saveButton.setForeground(new Color(220, 220, 220));
        saveButton.setText("SAVE");
        saveButton.setFont(new Font("Avenir Next", 1, 14)); // NOI18N
        saveButton.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                saveButtonMouseClicked(evt);
            }
        });

        GroupLayout popupBackground1Layout = new GroupLayout(popupBackground1);
        popupBackground1.setLayout(popupBackground1Layout);
        popupBackground1Layout.setHorizontalGroup(
            popupBackground1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(popupBackground1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(popupBackground1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(GroupLayout.Alignment.LEADING, popupBackground1Layout.createSequentialGroup()
                        .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tempTxtField))
                    .addGroup(GroupLayout.Alignment.LEADING, popupBackground1Layout.createSequentialGroup()
                        .addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1))
                    .addGroup(GroupLayout.Alignment.LEADING, popupBackground1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(cnclButton, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveButton, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE))
                    .addGroup(popupBackground1Layout.createSequentialGroup()
                        .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uvTxtField))
                    .addGroup(popupBackground1Layout.createSequentialGroup()
                        .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wsTxtField))
                    .addGroup(popupBackground1Layout.createSequentialGroup()
                        .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(huTxtField)))
                .addGap(69, 69, 69))
        );
        popupBackground1Layout.setVerticalGroup(
            popupBackground1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(popupBackground1Layout.createSequentialGroup()
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(popupBackground1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(tempTxtField)
                    .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(popupBackground1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(huTxtField)
                    .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(popupBackground1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(wsTxtField)
                    .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(popupBackground1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(uvTxtField))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(popupBackground1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(popupBackground1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(cnclButton, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(popupBackground1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(popupBackground1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cnclButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cnclButtonActionPerformed
        // In case of cancel TODO check that
        dispose();
    }//GEN-LAST:event_cnclButtonActionPerformed

    private void button1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    private void saveButtonMouseClicked(MouseEvent evt) {//GEN-FIRST:event_saveButtonMouseClicked
        String selectedDate = String.valueOf(comboBox1.getSelectedItem());
        double temp;
        try {
            temp = Double.parseDouble(tempTxtField.getText());
        } catch (NumberFormatException e) {
            showMessageDialog(null, "Value of Temperature must be a of type double");
            return;
        }
        int humidity;
        try {
            humidity = Integer.parseInt(huTxtField.getText());

            } catch (NumberFormatException e) {
                showMessageDialog(null, "Value of humidity must be a of type integer");
                return;
            }
        double wind;
            try {
                wind = Double.parseDouble(wsTxtField.getText());
            } catch (NumberFormatException e) {
                showMessageDialog(null, "Value of Windspeed must be a of type double");
                return;
            }
        int uv;
            try {
                uv = Integer.parseInt(uvTxtField.getText());
            } catch (NumberFormatException e) {
                showMessageDialog(null, "Value of Uv must be a of type double");
                return;
            }
        String desc = jTextField1.getText();
        Database connectDB = Database.getConnectionInstance();
        connectDB.updateMeteoDataByDateandCity(selectedCity, selectedDate, temp, humidity, uv, wind, desc);
        dispose();
    }//GEN-LAST:event_saveButtonMouseClicked

    private void button1MouseClicked(MouseEvent evt) {//GEN-FIRST:event_button1MouseClicked
        String selectedDate = String.valueOf(comboBox1.getSelectedItem());
        Database connectDB = Database.getConnectionInstance();
        List<String> DateCityList = connectDB.selectMeteoDataByDateandCity(selectedCity, selectedDate);
        tempTxtField.setText(DateCityList.get(0));
        huTxtField.setText(DateCityList.get(1));
        wsTxtField.setText(DateCityList.get(3));
        uvTxtField.setText(DateCityList.get(2));
        jTextField1.setText(DateCityList.get(4));
    }//GEN-LAST:event_button1MouseClicked

    private void comboBox1FocusGained(FocusEvent evt) {//GEN-FIRST:event_comboBox1FocusGained
        Database connectDB = Database.getConnectionInstance();
        List<String> DateList = connectDB.selectMeteoDataByDateCitys(selectedCity);
        Set<String> DateSet = new TreeSet<>(DateList);
        comboBox1.removeAllItems();
        for (String date : DateSet) {
            comboBox1.addItem(date);
        } 
    }//GEN-LAST:event_comboBox1FocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Button button1;
    private DialogButton cnclButton;
    private ComboBox comboBox1;
    private JLabel headingLabel;
    private JFormattedTextField huTxtField;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JPanel jPanel1;
    private JTextField jTextField1;
    private PopupBackground popupBackground1;
    private DialogButton saveButton;
    private JFormattedTextField tempTxtField;
    private JFormattedTextField uvTxtField;
    private JFormattedTextField wsTxtField;
    // End of variables declaration//GEN-END:variables
}
